# pyproject.toml

# This section defines the build system.
# It tells pip to use 'scikit-build-core' to build your package.
# scikit-build-core knows how to run CMake.
[build-system]
requires = ["scikit-build-core>=0.8", "cmake>=3.18", "numpy"]
build-backend = "scikit_build_core.build"



# This section contains the metadata for your package.
# This information will be displayed on PyPI.
[project]
name = "PyCSEMRI_fast"
version = "0.1.0"
description = "A package for CSEMRI with C++ accelerated components."
readme = "README.md"  # You should create a README.md file
authors = [
    { name = "Daiki Tamada", email = "dtamada@wisc.edu" },
]
license = { text = "GPL" } # Or another license like "BSD-3-Clause", etc.
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

# List your Python dependencies here.
# These will be installed by pip along with your package.
dependencies = [
    "numpy",
    'scipy',
    'scikit-image'
    # Add other dependencies like "scipy", "matplotlib", etc.
]

# Optional: For URLs like documentation, source code, etc.
[project.urls]
Homepage = "https://github.com/dtamadauw/PyCSEMRI_fast"
"Bug Tracker" = "https://github.com/dtamadauw/PyCSEMRI_fast/issues"

# This is the configuration for scikit-build-core.
[tool.scikit-build]
wheel.packages = ["package"]
sdist.reproducible = false



[tool.cibuildwheel]
# This is the most reliable way to enforce the build matrix.
skip = ["cp36-*", "cp37-*", "pp*"]

# This command will run before ANY wheel build.
# Crucially, it upgrades pip first, which is essential in older environments,
# then installs the necessary build tools.
before-build = "python -m pip install --upgrade pip && python -m pip install cmake"

# --- OVERRIDE FOR LINUX BUILDS ---
# This is a high-priority override to ensure a modern Docker image is used,
# completely preventing the use of the old Python 3.6 environment.
[[tool.cibuildwheel.overrides]]
select = "*-manylinux*"
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"


