# pyproject.toml

# This section defines the build system for legacy Python versions
[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake>=3.15",
    "numpy"  # General numpy requirement for the build process
]
build-backend = "setuptools.build_meta"



# This section contains the metadata for your package.
# This information will be displayed on PyPI.
[project]
name = "PyCSEMRI_fast"
version = "0.1.0"
description = "A package for CSEMRI with C++ accelerated components."
readme = "README.md"  # You should create a README.md file
authors = [
    { name = "Daiki Tamada", email = "dtamada@wisc.edu" },
]
license = { text = "GPL" } # Or another license like "BSD-3-Clause", etc.
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

# List your Python dependencies here.
# These will be installed by pip along with your package.
dependencies = [
    "numpy",
    'scipy',
    'scikit-image'
    # Add other dependencies like "scipy", "matplotlib", etc.
]

# Optional: For URLs like documentation, source code, etc.
[project.urls]
Homepage = "https://github.com/dtamadauw/PyCSEMRI_fast"
"Bug Tracker" = "https://github.com/dtamadauw/PyCSEMRI_fast/issues"

# This is the configuration for scikit-build-core.
[tool.scikit-build]
wheel.packages = ["package"]
sdist.reproducible = false


[tool.cibuildwheel]
# Explicitly build ONLY for Python 3.6 and 3.10
build = "cp36-* cp310-*"

# Skip PyPy builds
skip = "pp*"

# A general command to run before all builds
before-build = "python -m pip install --upgrade pip cmake"

# --- OVERRIDE FOR THE PYTHON 3.6 LINUX BUILD ---
# This section applies special rules only when building for Python 3.6
[[tool.cibuildwheel.overrides]]
select = "cp36-manylinux*"

# For the cp36 build, we need to install an older, compatible version of NumPy
before-build = "python -m pip install --upgrade pip && python -m pip install numpy<1.20 cmake"

