name: Build and Publish to PyPI

on:
  # This workflow runs when a new release is created.
  release:
    types: [created]
  # This allows you to run it manually from the Actions tab for testing.
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # This matrix tells GitHub to run the job on both Linux and macOS
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) For building ARM64 wheels on Linux runners
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.19.1
        env:
          # --- CORRECTED CONFIGURATION ---
          # Instead of skipping, we explicitly tell cibuildwheel which versions to build.
          # This builds for CPython 3.8 through 3.11.
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"
          
          # This tells cibuildwheel to install CMake before building.
          # We separate the linux command to be more explicit.
          CIBW_BEFORE_BUILD: "pip install cmake"
          CIBW_BEFORE_BUILD_LINUX: "pip install cmake && apt-get update && apt-get install -y build-essential"

      - name: Store the produced wheels as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish_wheels:
    name: Publish wheels to PyPI
    # This job only runs after all the build jobs are successful
    needs: build_wheels
    runs-on: ubuntu-latest
    
    # This step is only executed when a release is created, not on manual runs
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - name: Download all wheels from build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Use the API token you stored in GitHub secrets
          password: ${{ secrets.PYPI_API_TOKEN }}
