# .github/workflows/python-publish.yml

name: Build and Publish to PyPI

on:
  # This is now the ONLY way to trigger this workflow.
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # This matrix builds on both Linux and macOS.
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.19.1
        # All configuration is correctly handled by your pyproject.toml file.

      - name: Store the produced wheels as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish_wheels:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    
    # There is no 'if' condition here. If the build jobs succeed, this job WILL run.
    
    steps:
      - name: Download all wheels from build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This securely uses the API token you stored in GitHub secrets.
          password: ${{ secrets.PYPI_API_TOKEN }}

